name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set ENV
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run thumbo-core codemod
        working-directory: codemod
        run: npm i -g jscodeshift && yarn && node ./src/main.js
      - name: Build thumbo worker
        working-directory: thumbo-worker
        run: yarn && yarn build:prod
      - name: Build thumbo
        working-directory: thumbo
        run: yarn && yarn build:prod