name: Publish

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set ENV
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
            corepack enable
            pnpm --version
      - name: Run thumbo-core codemod
        working-directory: codemod
        run: |
            npm install -g jscodeshift
            pnpm install
            node ./src/main.js
      - name: Build thumbo worker
        working-directory: thumbo-worker
        run: pnpm install && pnpm build:prod
      - name: Build thumbo
        working-directory: thumbo
        run: pnpm install && pnpm build:prod
      - name: Copy README.md
        run: cp ./README.md ./thumbo/README.md
      - name: Update package version
        working-directory: thumbo
        run: pnpm version ${{ env.RELEASE_VERSION }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./thumbo/package.json
